### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.cordova.DownloadManager

### ISSUE THREAD

**Issue by souly1** [pierrejochem/cordova-plugin-downloadmanager#1]
Hi,
I've tried to use the plugin, but I keep getting this error seen via `adb logcat` and don't know how to pass it.
Any help would be welcomed.

Thanks

java.lang.ClassNotFoundException: org.apache.cordova.DownloadManager
03-20 13:57:25.899 25965 26083 W System.err: 	at java.lang.Class.classForName(Native Method)
03-20 13:57:25.899 25965 26083 W System.err: 	at java.lang.Class.forName(Class.java:324)
03-20 13:57:25.899 25965 26083 W System.err: 	at java.lang.Class.forName(Class.java:285)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-20 13:57:25.899 25965 26083 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-20 13:57:25.899 25965 26083 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 13:57:25.899 25965 26083 W System.err: 	at android.os.Looper.loop(Looper.java:148)
03-20 13:57:25.899 25965 26083 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-20 13:57:25.899 25965 26083 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.cordova.DownloadManager" on path: DexPathList[[zip file "/data/app/com.fitnessmeals.fitnessmealplanner-1/base.apk"],nativeLibraryDirectories=[/data/app/com.fitnessmeals.fitnessmealplanner-1/lib/x86, /data/app/com.fitnessmeals.fitnessmealplanner-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
03-20 13:57:25.899 25965 26083 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-20 13:57:25.899 25965 26083 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-20 13:57:25.899 25965 26083 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-20 13:57:25.899 25965 26083 W System.err: 	... 13 more
03-20 13:57:25.899 25965 26083 W System.err: 	Suppressed: java.lang.ClassNotFoundException: org.apache.cordova.DownloadManager
03-20 13:57:25.899 25965 26083 W System.err: 		at java.lang.Class.classForName(Native Method)
03-20 13:57:25.899 25965 26083 W System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-20 13:57:25.899 25965 26083 W System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-20 13:57:25.899 25965 26083 W System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-20 13:57:25.899 25965 26083 W System.err: 		... 14 more
03-20 13:57:25.899 25965 26083 W System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-20 13:57:25.899 25965 26083 I System.out: Error adding plugin org.apache.cordova.DownloadManager.
03-20 13:57:25.900 25965 26083 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
03-20 13:57:25.900 25965 26083 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
03-20 13:57:25.900 25965 26083 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
03-20 13:57:25.900 25965 26083 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
03-20 13:57:25.900 25965 26083 W System.err: 	at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
03-20 13:57:25.900 25965 26083 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-20 13:57:25.900 25965 26083 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-20 13:57:25.900 25965 26083 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 13:57:25.900 25965 26083 W System.err: 	at android.os.Looper.loop(Looper.java:148)
03-20 13:57:25.900 25965 26083 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pierrejochem** [comment]
I need to invest a bit time in this. Let you know as soon as I found a solution for it.
